config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles

  get 'signup', to: 'users#new'
  resources :users, execpt: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
  # The priority, is based upon order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :article_categories
	has_many :categories, through: :article_categories
	validates :title, presence: true, length: { minimum: 3, maximum: 50 }
	validates :description, presence: true, length: { minimum: 10, maximum: 300 }
	validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :update, :show, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	def new
		@article = Article.new
	end

  def create
		@article = Article.new(article_params)
		@article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

	def show
	end

	def index
		@articles = Article.paginate(page: params[:page], per_page: 3)
	end

	def edit
	end

	def update
		if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def destroy
		@article.destroy
		flash[:danger] = "Article was successfully deleted"
		redirect_to articles_path

	end

	private
		def set_article
			@article = Article.find(params[:id])
		end
		def require_same_user
			if current_user != @article.user && !current_user.admin?
				flash[:danger] = "You can only edit or delete your own articles"
				redirect_to root_path
			end
		end
		def article_params
			params.require(:article).permit(:title, :description, category_ids: [])
		end

end

app/views/articles/_articles.html.erb
<% obj.each do |article| %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="well well-lg">
				<div class="article-title">
					<%= link_to article.title, article_path(article) %>
				</div>
				<div class="article-body">
					<%= truncate(article.description, length: 100) %>
				</div>
				<div class="article-meta-details">
					<small>Created by:<%= article.user.username %>,
								<%= time_ago_in_words(article.created_at) %> ago,
								last updated: <%= time_ago_in_words(article.updated_at) %> ago </small>
				</div>
					<% if article.categories.any? %>
						<p>Categories: <%= render article.categories %></p>
					<% end %>
					<% if logged_in? && (current_user == article.user || current_user.admin?) %>
						<div class="article-actions">
							<%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %> 
							<%= link_to "Delete this article", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"}, class: "btn btn-xs btn-danger" %>
						</div>
					<% end %>
			</div>
		</div>
	</div>
<% end %>
			

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class="well">
	<%= form_for @article do |f| %>
		<div class="form-group">
			<%= f.label :title %><br/>
			<%= f.text_field :title, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :description %><br/>
			<%= f.text_area :description, rows: 10, class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|  %>
				<%= cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") +cb.text} %>
			<% end %>
		</div>

		<div class="form-group">
			<%= f.submit class: 'btn btn-primary'  %>
		</div>
	<% end %>

	<div class="text-center">
		
		[ <%= link_to "Cancel request & back to article listing", articles_path %> ] 
	</div>
</div>

app/views/articles/edit.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h1 class="text-center">Edit existing article</h1>
		<%= render 'form' %>
	</div>
</div>

app/views/articles/index.html.erb
<h1 class="text-center">Listing all articles</h1>
<div align="center">
	<%= will_paginate %>
</div>
<%= render 'articles', obj: @articles %>
<div align="center">
	<%= will_paginate %>
</div>

app/views/articles/new.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h1 class="text-center">Create an article</h1>
		<%= render 'form' %>
	</div>
</div>

app/views/articles/show.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h2 class="text-center"> Title: <%= @article.title %> </h2>
		<div class="well">
			<ul class="text-center list-unstyled">
				<li>Created by:</li>
				<li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
				<li class="font-sz"><%= link_to @article.user.username, user_path(@article.user) %></li>
				<li><small>
				<%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
				</small></li>
			</ul>
			<h4 class="text-center description"><strong>Description:</strong></h4>
			<hr> 			
			<%= simple_format(@article.description) %>
			<% if @article.categories.any? %>
				<p>Categories: <%= render @article.categories %></p>
			<% end %>
			<div class="article-actions">
				<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
					<%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
					<%= link_to "Delete this article", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"}, class: "btn btn-xs btn-danger" %>
				<% end %>
				<%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
			</div>
		</div>
	</div>
</div>